version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "src/code.cloudfoundry.org"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
    ignore:
    - dependency-name: "github.com/containernetworking/plugins" #locked at v0.6.0
    - dependency-name: "github.com/containernetworking/cni" #locked at v0.6.0
