---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: bbl-state
  - name: cf-networking-release-ci
  - name: istio-scaling

params:
  ENVIRONMENT: ~
  NUMBER_OF_APPS:
  CLEANUP_ORG:

run:
  path: cf-networking-release-ci/tasks/run-istio-scaling
