---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: cf-networking

params:
    ENVIRONMENT_NAME: ~

run:
  path: cf-networking-release-ci/ci/tasks/push-apps/task
