---
image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: cf-networking-release-ci
  - name: dev
  - name: release

outputs:
  - name: release-merged

run:
  path: cf-networking-release-ci/ci/tasks/merge-release/task
