---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: variables
  - name: cf-networking-release-ci

params:
  DATADOG_API_KEY: ~
  DATADOG_ENVIRONMENT_TAG: ~
  SLI_ORG: ~
  SLI_SPACE: ~
  SLI_APP_NAME: ~

run:
  path: cf-networking-release-ci/ci/tasks/sli-map-route/task
